#!/bin/bash
echo "Downloading the Arduino-CLI. A network connection is needed!"
#Arduino CLi
curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/bin sh

/usr/bin/arduino-cli board list
/usr/bin/arduino-cli core install arduino:avr

#Default Libraries
/usr/bin/chonosFirmwareManager --importLibrary -g chon-group/javino2arduino
/usr/bin/chonosFirmwareManager --importLibrary -g Martinsos/arduino-lib-hc-sr04
/usr/bin/chonosFirmwareManager --importLibrary -g arduino-libraries/LiquidCrystal